export const skills = [
  "HTML/CSS",
  "JavaScript",
  "React",
  "ReactNative",
  "NextJS",
  "Typescript",
  "TailwindCSS",
  "NodeJS",
  "ExpressJS",
  "NestJS",
  "C#/ASP.NET",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Prisma",
  "TypeORM",
  "Mongoose",
  "git/GitHub",
  "GithubActions",
  "Redis",
  "EFCore",
  "SQL Server",
];